export const mainContainer: string;
export const firstRowContainer: string;
export const firstRowContainerLeft: string;
export const firstRowContainerRight: string;
export const secondRowContainer: string;
export const secondRowGridContainer: string;
export const secondRowGridFirstRow: string;
export const secondRowGridSecondRow: string;
export const secondRowGridThirdRow: string;
