export const loginContainer: string;
export const loginRowLeft: string;
export const loginRowRight: string;
export const forgotPasswordBtn: string;
export const logInBtn: string;
export const formContainer: string;
export const formBtnContainer: string;
export const textBox: string;
export const symplyLogo: string;
