export const headerContainer: string;
export const categoryContainer: string;
export const blogContainer: string;
export const blogGrid: string;
export const widgetContainer: string;
export const button: string;
export const buttonContainer: string;
export const secondRowContainer: string;
export const secondRowInnerContainer: string;
export const secondRowInnerRowLeft: string;
export const secondRowInnerRowRight: string;
export const formContainer: string;
export const inputContainer;
